#!/usr/bin/php
<?php

 	/*
	103architecte.php for  in /home/bertra_v/tek_1/Maths/103architecte
   
	Made by Florent Bertrand
	Login   <bertra_v@epitech.net>
   
	Started on  Mon Dec  8 14:14:35 2014 Florent Bertrand
   Last update Thu Dec 11 15:57:57 2014 Florent Bertrand
	*/

	include 'check_option.php';
?>